// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1dd24c9c5cde4bb81a8404fea65ed0f3e8fff54e/github-electron/github-electron.d.ts
// Type definitions for Electron v0.37.4
// Project: http://electron.atom.io/
// Definitions by: jedmao <https://github.com/jedmao/>, rhysd <https://rhysd.github.io>, Milan Burda <https://github.com/miniak/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare module 'electron' {
    import * as main from 'electron/@main';

    export * from 'electron/@main';

    global {
        interface NodeRequireFunction {
            (moduleName: 'electron'): typeof main;
        }
    }
}