// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1dd24c9c5cde4bb81a8404fea65ed0f3e8fff54e/github-electron/github-electron.d.ts
// Type definitions for Electron v0.37.4
// Project: http://electron.atom.io/
// Definitions by: jedmao <https://github.com/jedmao/>, rhysd <https://rhysd.github.io>, Milan Burda <https://github.com/miniak/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare module 'electron' {
    import { WebViewElement, BrowserWindowProxy } from 'electron/@render';
    import * as render from 'electron/@render';

    export * from 'electron/@render';

    global {
        interface Document {
            createElement(tagName: 'webview'): WebViewElement;
        }

        // https://github.com/atom/electron/blob/master/docs/api/window-open.md

        interface Window {
            /**
             * Creates a new window.
             */
            open(url: string, frameName?: string, features?: string): BrowserWindowProxy;
        }

        // https://github.com/atom/electron/blob/master/docs/api/file-object.md

        interface File {
            /**
             * Exposes the real path of the filesystem.
             */
            path: string;
        }

        interface NodeRequireFunction {
            (moduleName: 'electron'): typeof render;
        }
    }
}